---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1c5yffvtfj3h3p6mpykeuynxwwqepw38pk0n4jl5ag0unmuqy5gyspy4c8y
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1c5yffvtfj3h3p6mpykeuynxwwqepw38pk0n4jl5ag0unmuqy5gyspy4c8y
