---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   finalizers:
#   - kubernetes.io/pvc-protection
#   name: home-assistant-config-pvc
#   namespace: home
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: longhorn
#   volumeMode: Filesystem
