---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: hkotel/mealie
      tag: 4.2.1
    env: 
      TZ: "America/Denver"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik 
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/appName: "Mealie"
          hajimari.io/enable: "true"
          hajimari.io/icon: "food"
        hosts:
          - host: "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "mealie.${SECRET_DOMAIN}"
            secretName: "mealie-tls"
    persistence:
      config:
        enabled: true
        existingClaim: "mealie-pvc"
    # # addons:
    #   codeserver:
    #     enabled: true
    #     image:
    #       repository: codercom/code-server
    #       tag: 4.3.0
    #     env:
    #       TZ: "America/Denver"
    #     workingDir: "/config"
    #     args:
    #       - --user-data-dir
    #       - "/config/.vscode"
    #       - --auth
    #       - "none"
    #     ingress:
    #       enabled: true
    #       annotations:
    #         kubernetes.io/ingress.class: traefik 
    #         external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    #         external-dns/is-public: "true"
    #         cert-manager.io/cluster-issuer: "letsencrypt-production"
    #         traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    #       hosts:
    #         - host: haconfig.${SECRET_DOMAIN}
    #           paths:
    #           - path: /
    #             pathType: Prefix
    #       tls:
    #         - hosts:
    #             - "haconfig.${SECRET_DOMAIN}"
    #           secretName: "haconfig-tls"
    #     volumeMounts:
    #     - name: config
    #       mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi    
