apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
    namespace: networking
stringData:
    cloudflare_email: ENC[AES256_GCM,data:l3jyK+5DM9Q3by7AoojWvjXb2ek=,iv:O7QKqd8pZReUkdFe1KHy+0GvgUCrh/5/EPVuAKZZeYU=,tag:y2hk1bPOeCJaX1SeJpgqlg==,type:str]
    cloudflare_apikey: ENC[AES256_GCM,data:6Vhl6BRwNtKFyftpvZDZrcxiySTf27AabclNG33JafelcOrfJw==,iv:Hoijmt1BmLrwBu2EkJFYy8SX1oPLvLkSDR9BE+Y3/lI=,tag:DScaUCqDE7NftA8WW850uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5yffvtfj3h3p6mpykeuynxwwqepw38pk0n4jl5ag0unmuqy5gyspy4c8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbGJTNjlmd1lJcnBpSnNJ
            Q0s2T3RURERscUNzcjlPOUx2ck1PekJadTJvCkJWWGdrbldUenhkdWk3bStTNHRR
            WEk4SWVueFZWb2pNdXdaNTdmc0E2NFkKLS0tIFV0bXhPWTFOUDBISytiNnE5dEZY
            WEkwdEI3Nmh0MCtJclR2U3Faa3pwamsKw5WYrr12XUMajmg2EWCHs5/UHPMVfXEz
            9PHbv+aOoYuDXQNBMHg0jJf0AUHt9MTjE9Oobf6Y9fdbcPhYwg7b4w==
            -----END AGE ENCRYPTED FILE-----
    mac: ENC[AES256_GCM,data:mj68CQ8sK6L5FrsG5lP5sfVwaYnVewS5am+t/uZl15i/y8e0EQRzPl7hyklPa0otyWKL0WhgvYjXkanLuvCHs1+AiitagOUek5BHpNuRz7wmAsx5BvCkTLrtupu5/IfZTjIqSWOpKFNy/G/oqbTbljcr3A7x2qi30SWL95gepxM=,iv:pjg5ujX72dezMZSGS4bq0nSvNLqXxAWjz25FGVvdjtA=,tag:k/J5xKzraOuJwLgB1DtaFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1