---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lychee
  namespace: photography
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lychee
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: "America/Denver"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik 
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/appName: "HA"
          hajimari.io/enable: "true"
          hajimari.io/icon: "camera"
        hosts:
          - host: "gkphoto.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "gkphoto.${SECRET_DOMAIN}"
            secretName: "lychee-tls"
    persistence:
      config:
        enabled: true
        mountPath: /conf
        existingClaim: lychee-config-pvc

      uploads:
        enabled: true
        mountPath: /uploads
        existingClaim: lychee-uploads-pvc

      sym:
        enabled: true
        mountPath: /sym
        existingClaim: lychee-sym-pvc
