---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/stable
      chart: rancher
      version: 2.6.3
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  interval: 15m0s
  timeout: 20m
  values:
    replicas: 1
    ingress:
      enabled: false
