---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1800Gi
  storageClassName: nfs-client

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-config
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: nfs-client
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-config-longhorn
#   namespace: media
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 15Gi
#   storageClassName: longhorn
#   volumeMode: Filesystem
