---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.1.5286-34f965be8
    env:
      TZ: "America/Denver"
    # podSecurityContext:
    #   supplementalGroups:
    #     - 44
    #     - 109
    #     - 100
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        #NOT sure about the lines below
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: https    
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-media
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume1/Media/plex
        mountPath: /media
        readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    resources:
      requests:
        cpu: 1000m
        memory: 1000Mi
      limits:
        memory: 10000Mi
