---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.25.2.5319-c43dc0277
      pullPolicy: IfNotPresent

    env:
      TZ: "America/Denver"
      ALLOWED_NETWORKS: 10.0.0.0/255.255.255.0
      PLEX_CLAIM: claim-zUasSSXJF3HUAsUFCAks
      PLEX_PREFERENCE_1: "FriendlyName=KingPlex"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hajimari.io/appName: "Plex"
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"

        hosts:
          - host: plex.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tls.plex
            hosts:
              - plex.${SECRET_DOMAIN}
    persistence:
      data:
        enabled: true
        existingClaim: "plex-media"
      config:
        enabled: true
        existingClaim: "plex-config-longhorn"
