apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - metallb-system.yaml
  - networking.yaml
  - mealie.yaml
  - media.yaml
  - cattle-system.yaml
  - home.yaml
